version: '2'

networks:
  puppet:
    driver: bridge

services:
  puppet:
    image: puppet_master
    ports:
      - "8000:8000"
      - "2222:22"
    environment:
      JAVA_ARGS: "-Xms256m -Xmx256m -XX:MaxPermSize=256m"
    volumes:
      - /Users/vbrednikov/puppet/workspace:/workspace
    networks:
      - puppet
    container_name: puppet
    domainname: codespaces.io
    hostname: puppet
    restart: always

  node1:
    image: puppet_node
    ports:
       - "8081:8080"
       - "81:80"
    networks:
      - puppet
    container_name: node1
    domainname: codespaces.io
    hostname: node1
    restart: always

  node2:
    image: puppet_node
    ports:
       - "8082:8080"
       - "82:80"
    networks:
      - puppet
    container_name: node2
    domainname: codespaces.io
    hostname: node2
    restart: always

  node3:
    image: puppet_node
    ports:
      - "8083:8080"
      - "83:80"
    networks:
      - puppet
    container_name: node3
    domainname: codespaces.io
    hostname: node3
    restart: always

  node4:
    image: puppet_node
    ports:
      - "8084:8080"
      - "80:80"
      - "3306:3306"
    networks:
      - puppet
    container_name: node4
    domainname: codespaces.io
    hostname: node4
    restart: always
