#   "image_codespaces/puppet-master:v0.1.3"
#   "image_codespaces/puppet-node-centos-6:v0.1.3"


- hosts: node
  connection: docker
  gather_facts: no
  become: yes
  tasks:
   - name: Request certificate
     shell: /bin/bash -l -c "/opt/puppetlabs/bin/puppet agent -t" || true
     register: result
   - name: debug
     debug:
       var: result
       verbosity: 1


- hosts: puppet
  connection: docker
  become: yes
  tags:
   - sign
  handlers:
   - name: restart puppetserver
     service: name=puppetserver state=restarted

  tasks:
   - name: Show incoming certs
     shell:  /opt/puppetlabs/bin/puppet cert list
     register: result
   - name: debug
     debug:
       var: result
       verbosity: 1
   - name: Sign all certs
     shell:  /opt/puppetlabs/bin/puppet cert sign -y --all
     register: result
   - name: debug
     debug:
       var: result
       verbosity: 1
   - name: move master-code-dir to /workspace
     shell: cp -a /etc/puppetlabs/code /workspace
     args:
       creates: /workspace/code
   - name: correct master-code-dir
     lineinfile:
       path: /etc/puppetlabs/puppetserver/conf.d/puppetserver.conf
       regexp: '^\s+master-code-dir'
       line: "    master-code-dir: /workspace/code"
     notify: restart puppetserver

- hosts: node
  connection: docker
  gather_facts: no
  become: yes
  tasks:
   - name: apply configuration
     shell: /bin/bash -l -c "/opt/puppetlabs/bin/puppet agent -t" || true
     register: result
   - name: debug
     debug:
       var: result
       verbosity: 1


